student_help/app_admin/urls.py
from django.urls import path
from .views import *
from .views import user_postes
from .views import add_poste
from .views import UpdatePoste
from .views import DeletePoste
#from .views import AddPoste
urlpatterns = [
  path('', dashboard, name="dashboard"),
  path('my_postes/', user_postes, name='my_postes'),
  path('add-poste/', add_poste, name='add-poste'),
#  path('add-poste/', AddPoste.as_view(), name='add-poste'),
  path('update-poste/<int:pk>', UpdatePoste.as_view(), name='update-poste'),
  path('delete-poste/<int:pk>', DeletePoste.as_view(), name='delete-poste'),
]

student_help/student_auth/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import login_view, register, logout_view

urlpatterns = [
    path('login/', login_view, name='login'),
    path('register/', register, name='register'),
    path('logout/', logout_view, name='logout'),
]

student_help/student_help/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib import admin, auth
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from student_app.views import home,detail,search,stage,contact
#from student_auth.views import login
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name = "home"),
    path('Poste/<int:id>', detail, name="detail"),
    path('Poste/recherche', search, name="search"),
    path('auth/', include("student_auth.urls")),
    path('my_admin/', include("app_admin.urls")),
     path('contact/', contact, name='contact'),

    #path('login/',auth_views.LoginView.as_view(template_name='registration/login.html'), name = 'login'),
    #path('login/', auth_views.LogoutView.as_view(template_name='registration/logout.html'), name = 'logout'),
]+ static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)



#http://127.0.0.1:8000/poste/3 => detail(request,id_poste=3)

student_help/student_auth/forms.py
from django import forms

class LoginForm(forms.Form):
  username = forms.CharField(label="Nom Etudiant",widget=forms.TextInput(attrs={'class':'form-control'}))
  pwd = forms.CharField(label="Mot de passe",widget=forms.PasswordInput(attrs={'class':'form-control'}))

#username = CharField(name="username",label="nom utilisateur")
#username.name='username'

class RegisterForm(forms.Form):
  username = forms.CharField(label="Nom Etudiant",widget=forms.TextInput(attrs={'class':'form-control'}))
  pwd = forms.CharField(label="Mot de passe",widget=forms.PasswordInput(attrs={'class':'form-control'}))
  pwd_confirm = forms.CharField(label="Mot de passe de confirmation",widget=forms.PasswordInput(attrs={'class':'form-control'}))

student_help/student_auth/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login as auth_login
from django.contrib.auth.models import User
from django.contrib.auth import logout as auth_logout
from django.contrib import messages
from .forms import LoginForm, RegisterForm

def login_view(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            pwd = form.cleaned_data['pwd']
            user = authenticate(username=username, password=pwd)
            if user is not None:
                auth_login(request, user)  # Use auth_login to avoid conflict
                return redirect('home')
            else:
                messages.error(request, 'Authentication failed!')
                return render(request, 'login.html', {'form': form})
        else:
            for field in form.errors:
                form[field].field.widget.attrs['class'] += ' is-invalid'
            return render(request, 'login.html', {'form': form})
    else:
        form = LoginForm()
        return render(request, 'login.html', {'form': form})

def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            pwd = form.cleaned_data['pwd']
            user = User.objects.create_user(username=username, password=pwd)
            if user is not None:
                return redirect("login")
            else:
                messages.error(request, 'Account creation failed!')
                return render(request, 'register.html', {'form': form})
        else:
            return render(request, 'register.html', {'form': form})
    else:
        form = RegisterForm()
        return render(request, 'register.html', {'form': form})

def logout_view(request):
    auth_logout(request)
    messages.success(request, "You have successfully logged out.")
    return redirect('login')

student_help/student_auth/templates/login.html
{% extends 'base.html' %}
{% block title %} aa {% endblock %}
{% block content %}
<div class="container">
  <div class="col-md-12 mt-5">
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-danger text-center">
      <strong>{{message}}</strong>
    </div>
    {% endfor %}
    {% endif %}

    <form action="" method="POST" novalidate>{% csrf_token %}
      <div class="card">
        <div class="card-header text-center">
          <i class="fas fa-user"></i>
          Connexion au Student
        </div>
        <div class="card-body">
          <label for="id_usename">Nom Etudiant</label>
          {% if form.username.errors %}
          {% for error in form.username.errors %}
          <div class="div-error" {{form.username.name}}><small class="text-danger">{{error}}</small></div>
          {% endfor %}
          {% endif %}
          {{form.username}}
          <label for="id_pwd">Mot de passe</label>
          {% if form.pwd.errors %}
          {% for error in form.pwd.errors %}
          <div><small class="text-danger">{{error}}</small></div>
          {% endfor %}
          {% endif %}
          {{form.pwd}}
        </div>
        <div class="card-footer">
          <button class="btn btn-primary btn-block">SE CONNECTER</button>
        </div>
        <p class="mt-2">Vous n'avez pas de compts? <a href="{% url 'register' %}">Inscrivez-vous</a></p>

      </div>

    </form>
  </div>
</div>
{% endblock %}
<script>
  $(document).ready(function() {
      $('input').keyup(function(){
        let textSaisi = $(this).val();

        let attrName = $(this).val();
        let validatorElement = ".div-error"+attrName;
        if(textSaisi === ""){
          if($(this).hasClass('is-invalid')){
            $(this).addClass('is-invalid');
            $(validatorElement).show();
          }
        } else {
          $(this).removeClass('is-invalid');
        }
      })
  })
</script>
{% block scripts %}

{% endblock %}

student_help/student_auth/templates/register.html
{% extends 'base.html' %}
{% block title %} Creation de compte Student {% endblock %}
{% block content %}
<div class="container">
  <div class="col-md-12 mt-5">
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-danger text-center">
      <strong>{{message}}</strong>
    </div>
    {% endfor %}
    {% endif %}

    <form action="" method="POST" novalidate>{% csrf_token %}
      <div class="card">
        <div class="card-header text-center">
          <i class="fas fa-user-lock"></i>
          Création de compte
        </div>
        <div class="card-body">
          {{form}}
        </div>
        <div class="card-footer">
          <button class="btn btn-primary btn-block">créer le compte</button>
        </div>
      </div>

    </form>
  </div>
</div>
{% endblock %}

{% block scripts %}

{% endblock %}